INSERT INTO brands (name, description, cnpj) VALUES ('Acme Corporation', 'Vestibulum vel lorem vitae tellus malesuada eleifend commodo sed leo.', '26.355.751/3171-69');
INSERT INTO brands (name, description, cnpj) VALUES ('Globex Corporation', 'Fusce posuere eros eget sagittis fermentum.', '50.868.414/4796-59');
INSERT INTO brands (name, description, cnpj) VALUES ('Soylent Corp', 'Aenean egestas nisi eu sem varius consectetur.', '82.085.033/8007-00');
INSERT INTO brands (name, description, cnpj) VALUES ('Initech', 'Aenean id lacus in lectus iaculis faucibus id sed libero.', '37.980.281/7962-44');
INSERT INTO brands (name, description, cnpj) VALUES ('Bluth Company', 'Maecenas ut ligula mollis nibh finibus luctus in et lectus.', '62.885.507/8173-07');
INSERT INTO brands (name, description, cnpj) VALUES ('Umbrella Corporation', 'Fusce et enim pellentesque, pulvinar ex eget, gravida dolor.', '47.129.997/6372-87');
INSERT INTO brands (name, description, cnpj) VALUES ('Hooli', 'Ut efficitur sem vitae accumsan eleifend.', '85.255.928/4684-59');
INSERT INTO brands (name, description, cnpj) VALUES ('Vehement Capital Partners', 'Donec interdum urna tristique lorem condimentum, a mollis magna rhoncus.', '12.564.009/7177-37');
INSERT INTO brands (name, description, cnpj) VALUES ('Massive Dynamic', 'Nunc pulvinar lacus ut erat commodo, bibendum interdum lacus fermentum.', '59.263.936/7402-26');
INSERT INTO brands (name, description, cnpj) VALUES ('Wonka Industries', 'Praesent ut orci eget tellus consectetur mattis.', '93.009.761/5646-98');
INSERT INTO brands (name, description, cnpj) VALUES ('Stark Industries', 'Suspendisse pharetra lacus vel augue eleifend fringilla.', '91.346.474/6183-31');
INSERT INTO brands (name, description, cnpj) VALUES ('Gekko & Co', 'Fusce et enim pellentesque, pulvinar ex eget, gravida dolor.', '58.561.564/8586-76');
INSERT INTO brands (name, description, cnpj) VALUES ('Wayne Enterprises', 'Mauris mollis ante quis turpis suscipit faucibus.', '18.047.334/3480-01');
INSERT INTO brands (name, description, cnpj) VALUES ('Bubba Gump', 'Duis sed diam id leo consectetur mattis ut non nisl.', '23.402.827/1827-68');
INSERT INTO brands (name, description, cnpj) VALUES ('Cyberdyne Systems', 'Sed consequat velit sit amet suscipit condimentum.', '22.633.014/6580-76');
INSERT INTO brands (name, description, cnpj) VALUES ('Genco Pura Olive Oil Company', 'Praesent ut orci eget tellus consectetur mattis.', '71.730.647/3446-76');
INSERT INTO brands (name, description, cnpj) VALUES ('The New York Inquirer', 'Donec interdum urna tristique lorem condimentum, a mollis magna rhoncus.', '62.971.649/1955-46');
INSERT INTO brands (name, description, cnpj) VALUES ('Duff Beer', 'Ut efficitur sem vitae accumsan eleifend.', '35.978.089/4106-20');
INSERT INTO brands (name, description, cnpj) VALUES ('Olivia Pope & Associates', 'Ut efficitur sem vitae accumsan eleifend.', '70.366.687/7930-45');
INSERT INTO brands (name, description, cnpj) VALUES ('Sterling Cooper', 'Aenean egestas nisi eu sem varius consectetur.', '16.188.423/5750-88');
INSERT INTO brands (name, description, cnpj) VALUES ('Ollivanders Wand Shop', 'Suspendisse tincidunt leo sit amet diam ornare, eu molestie orci condimentum.', '32.674.825/2135-13');
INSERT INTO brands (name, description, cnpj) VALUES ('Cheers', 'Etiam auctor sem ut volutpat ullamcorper.', '53.866.366/7305-67');
INSERT INTO brands (name, description, cnpj) VALUES ('Krusty Krab', 'Duis vestibulum nulla nec tempor ultrices.', '46.723.702/6870-99');
INSERT INTO brands (name, description, cnpj) VALUES ('Good Burger', 'Duis ultricies nulla vel mi vehicula, eu semper erat sagittis.', '80.382.824/6004-04');

INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('baking soda', 'Duis vestibulum nulla nec tempor ultrices.', 92.03, 341, '0', 10, 13);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('rabbits', 'Nunc vel lacus a ligula vehicula congue.', 4.21, 726, '0', 13, 5);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('asiago cheese', 'Nullam sed tellus sit amet sem sollicitudin sollicitudin.', 86.66, 587, '1', 40, 4);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('capers', 'Vivamus et nulla pretium, viverra sem vel, vehicula purus.', 35.28, 845, '0', 67, 22);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('cloves', 'Fusce et enim pellentesque, pulvinar ex eget, gravida dolor.', 52.69, 440, '0', 81, 15);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('oregano', 'Mauris mollis ante quis turpis suscipit faucibus.', 42.24, 8, '1', 42, 9);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('coconuts', 'Suspendisse ac turpis sed urna accumsan scelerisque.', 63.13, 921, '0', 93, 14);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('almond extract', 'Quisque efficitur mi ut varius finibus.', 30.01, 579, '0', 95, 23);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('vinegar', 'Nullam efficitur dolor in risus pretium pharetra.', 94.47, 555, '0', 40, 20);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('rhubarb', 'Aenean tincidunt elit sit amet est pharetra ultrices sit amet a urna.', 13.65, 855, '0', 35, 6);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('moo shu wrappers', 'Nullam sed tellus sit amet sem sollicitudin sollicitudin.', 55.44, 802, '0', 37, 22);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('pink beans', 'Aenean tincidunt elit sit amet est pharetra ultrices sit amet a urna.', 57.68, 953, '0', 1, 18);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('mustard', 'Morbi venenatis massa et nulla feugiat, vel pulvinar turpis consectetur.', 11.01, 126, '0', 89, 24);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('provolone', 'Nulla sit amet velit sit amet nibh auctor auctor.', 6.33, 250, '0', 56, 3);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('red pepper flakes', 'Sed sed quam in leo vestibulum lacinia hendrerit a nulla.', 92.24, 564, '1', 95, 5);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('balsamic vinegar', 'Proin scelerisque eros non dui maximus, ut blandit elit pulvinar.', 47.72, 824, '1', 44, 19);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('condensed milk', 'Mauris mollis ante quis turpis suscipit faucibus.', 46.74, 353, '1', 63, 14);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('pico de gallo', 'Nulla sit amet velit sit amet nibh auctor auctor.', 75.55, 713, '0', 78, 24);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('haddock', 'Suspendisse tincidunt leo sit amet diam ornare, eu molestie orci condimentum.', 41.40, 224, '1', 37, 3);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('brown sugar', 'Etiam iaculis est ut scelerisque elementum.', 39.88, 261, '0', 53, 17);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('steak', 'Nunc pulvinar lacus ut erat commodo, bibendum interdum lacus fermentum.', 16.91, 588, '0', 13, 8);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('pork', 'Quisque efficitur mi ut varius finibus.', 39.35, 575, '1', 86, 6);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('raspberries', 'Maecenas ut ligula mollis nibh finibus luctus in et lectus.', 57.52, 838, '1', 44, 20);
INSERT INTO products (name, description, sale_price, total_quantity, actived, min_quantity, brand_id) VALUES ('celery', 'Mauris mollis ante quis turpis suscipit faucibus.', 8.69, 522, '1', 39, 19);
